AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  crud
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3


Resources:
  getVehicles:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: crud/
      Handler: vehicles.handler
      Runtime: nodejs12.x
      Policies: 
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:DeleteItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/Vehicles'
        - DynamoDBCrudPolicy:
            TableName: Vehicles
      Events:
        getVehicles:
          Type: Api 
          Properties:
            Path: /vehicles/{id}
            Method: any
        allOperations:
          Type: Api 
          Properties:
            Path: /vehicles
            Method: post
   
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "Vehicles"
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE


#https://a3h9s581y7.execute-api.us-east-1.amazonaws.com/Prod/hello/